#!/usr/bin/env python3
print("Hello, I am script")

Переименовываем
$ cp helloworld.py helloworld

Делаем исполняемым
$ chmod +x helloworld

Добавляем путь
$ PATH=$PATH:/home/alex/alex_scripts

Или расположить файл в /usr/games
$ echo $PATH
/home/alex/.local/bin:/usr/local/sbin:
/usr/local/bin:/usr/sbin:/usr/bin:
/sbin:/bin:/usr/games:/usr/local/games:
/snap/bin:/snap/bin

Из любой папки пишем нашу команду
$ helloworld

Hello, I am script